version: '3'
services:
    mysql_draw_teams:
        image: mysql:8.0
        container_name: mysql_draw_teams
        restart: always
        environment:
            MYSQL_DATABASE: 'drawteams'
            MYSQL_USER: 'dtuser'
            MYSQL_PASSWORD: 'p@ssword!'
            MYSQL_ROOT_PASSWORD: 'p@ssword!'
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - draw_teams_network

    # nginx-api:
    #     container_name: "nginx_draw_teams"
    #     image: nginx
    #     volumes:
    #         - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    #         - ./backend-laravel:/var/www/html
    #         - ./nginx/logs:/var/log/nginx
    #     ports:
    #         - 7001:80
    #     restart: always
    #     depends_on:
    #         - node
    #     links:
    #         - node
    php8_draw_teams:
        container_name: "php8_draw_teams"
        build: ./backend-laravel
        image: fsphp8
        restart: always
        volumes:
            # - ./php8/php.ini:/usr/local/etc/php/conf.d/php.ini
            # - ./php8/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./backend-laravel:/var/www/html
        ports:
            - 6001:9000
        networks:
            - draw_teams_network
        # entrypoint: /usr/local/bin/docker-entrypoint.sh
        # command: >
        #     bash -c "composer install --no-interaction --optimize-autoloader --prefer-dist --no-scripts
        #     && echo 'Migrando estrutura de dados.'
        #     && php artisan migrate --env=.env.local
        #     && echo 'Iniciando servidor.'
        #     && php artisan serve --env=.env.local --host=0.0.0.0 --port=9000"
    
    node:
        container_name: node_draw_teams
        restart: always
        build:
            context: ./frontend-reactjs
            dockerfile: dockerfile
        ports:
            - '8080:3000'
        volumes:
            - ./frontend-reactjs:/usr/src/app
        networks:
            - draw_teams_network

    # composer:
    #     container_name: "composer"
    #     image: composer
    #     volumes:
    #         - ./backend-laravel:/app
    #     command: install

volumes:
  mysql-data:
    driver: local

networks:
  draw_teams_network:
    driver: bridge